FROM ubuntu:groovy

WORKDIR /home/
ENV P4C_DEPS bison \
             build-essential \
             cmake \
             git \
             flex \
             libboost-dev \
             libboost-graph-dev \
             libboost-iostreams-dev \
             libfl-dev \
             libgc-dev \
             libgmp-dev \
             pkg-config \
             python3 \
             python3-pip \
             python3-setuptools

ENV P4C_EBPF_DEPS libpcap-dev \
             libelf-dev \
             zlib1g-dev \
             llvm \
             clang \
             libprotobuf-dev \
             protobuf-compiler \
             iproute2 \
             tcpdump \
             iptables

ENV P4C_PIP_PACKAGES pyroute2 \
                     ply==3.8 \
                     scapy==2.4.0

RUN DEBIAN_FRONTEND="noninteractive" apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends $P4C_DEPS
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends $P4C_EBPF_DEPS
# in some cases wheel is needed to install pip packages
RUN pip3 install wheel 
RUN pip3 install $P4C_PIP_PACKAGES
