FROM stolsma/p4c-base:latest

WORKDIR /home/

# p4c download begin
RUN git clone https://github.com/p4lang/p4c.git && \
    cd p4c && \
    git submodule update --init --recursive && \
    git submodule update --recursive && \
    mkdir extensions
# p4c download end


# copy xdp into the extension folder
COPY . /home/p4c/extensions/p4c-xdp
RUN ln -s /home/p4c /home/p4c/extensions/p4c-xdp


# build p4c and p4c-xdp
RUN cd /home/p4c/ && \
    python3 backends/ebpf/build_libbpf && \
    mkdir -p build && \
    cd build && \
    cmake .. && \
    make -j `getconf _NPROCESSORS_ONLN` && \
    make install && \
    cd ..