name: Create p4c-base image

on:
  push:
    # Publish if branch is `p4vswitch`
    branches:
      - p4vswitch
    # or publish if `v1.2.3` tags as releases.
    tags:
      - v*
    
    # but only if the base p4c Dockerfile changes!
    paths:
      - 'docker/Dockerfile-p4c-base' 

jobs:
  # Push image to Docker hub.
  create_image:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push p4c-base image to Github Package store
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile-p4c-base
          repository: stolsma/p4c-base
          tags: latest